### ISSUE TITLE
Ruby?

### ISSUE THREAD

**Issue by tmcw** [emacsen/changemonger#18]
Dumb question perhaps, but would it ever be a goal for changemonger to be usable in the rails port directly as a gem (and thus, yes, sigh, lame, a ruby port)? Or is the architecture more like a multi-server system?

**Comment by ppawel** [comment]
+1 for Ruby port. I have integrated Changemonger into Changeset Activity Publisher but it is extremely hackish integration. Being able to use Changemonger (or at least the core) as a library (gem) would be a perfect solution for me.

[1] https://github.com/ppawel/osm-activity-publishers/tree/master/changeset-publisher

**Comment by emacsen** [comment]
Tom,

It's not a dumb question, but it's a question of resources.

There would be some advanages of having the code in Ruby instead of Python (one of which would be the DSL I want to write, which would be easier in Ruby than Python), but there are also libraries that I rely on in Python that I would need to find replacements for.

The beta (not on github yet) is more OO than the current version, so it would fit Ruby's model just fine; the main question in my mind is "If I build it, will I get more contributors?"

If not- then I might as well continue with the current development, since it doesn't really much  whether the code to get data back from CM is done via a library call or via a network call (one via a local socket, for example).

Thoughts?

**Comment by tmcw** [comment]
> The beta (not on github yet) is more OO than the current version, so it would fit Ruby's model just fine; the main question in my mind is "If I build it, will I get more contributors?"

Ha, well that's another question - why isn't the beta on GitHub yet? I'm at least interested in writing tests, and assumed that this was the thing itself. I guess I should hold off that work until this (the real version) is open.

**Comment by tmcw** [comment]
Welp, @emacsen ping back when this code is actually master.

**Comment by emacsen** [comment]
It's not functional _at all_ right now. For the changes I planned for the beta to work, I need to make a bunch of internal changes.

I'll upload it to another (non-master) branch later this week for examination, but the code won't work that early
